name: MyLobby
author: Marvin2k0
version: 2017.02.11
language: German
main: de.marvinleiers.lobbysystem.Main
commands:
  setspawn:
    description: Sets the lobby spawn
    permission: mylobby.setspawn
  spawn:
    description: Teleports to the lobby spawn
    aliases: [l, hub, lobby]